#ifndef QSPOTIFYLOGGING_H
#define QSPOTIFYLOGGING_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(qlsAudioThread)
Q_DECLARE_LOGGING_CATEGORY(qlsCacheManager)
Q_DECLARE_LOGGING_CATEGORY(qlsPlaylist)
Q_DECLARE_LOGGING_CATEGORY(qlsPlaylistContainer)
Q_DECLARE_LOGGING_CATEGORY(qlsSession)
Q_DECLARE_LOGGING_CATEGORY(qlsTrack)

#endif /* QSPOTIFYLOGGING_H */
